
-- Column profiling script for use in discovery.
-- Run a select * from src and step through each.

SELECT j.key AS column_name,
       count(*) FILTER (WHERE j.value IS NOT NULL AND j.value <> '') AS populated,
       round(100.0 * count(*) FILTER (WHERE j.value IS NOT NULL AND j.value <> '')
             / count(*), 1) AS pct_filled,
       count(DISTINCT j.value) FILTER (WHERE j.value IS NOT NULL AND j.value <> '') AS distinct_values
FROM   dsc.pp t,
       LATERAL jsonb_each_text(to_jsonb(t)) AS j(key, value)
GROUP  BY j.key
ORDER  BY populated, j.key;

WITH profile AS (
  SELECT j.key AS column_name,
         count(*) FILTER (WHERE j.value IS NOT NULL AND j.value <> '') AS populated
  FROM   dsc.pp t, LATERAL jsonb_each_text(to_jsonb(t)) AS j(key, value)
  GROUP  BY j.key
)
SELECT string_agg('"' || column_name || '"', ', ' ORDER BY column_name)
FROM   profile WHERE populated > 0;


SELECT 'CREATE TABLE stg.' || lower('CHARGES') || ' (' || E'\n' ||
       string_agg('    "' || column_name || '" text', ',' || E'\n' ORDER BY column_name) ||
       ',' || E'\n    loaded_at timestamp NOT NULL DEFAULT clock_timestamp()' || E'\n);'
FROM   dsc.column_profile
WHERE  source_table = 'CHARGES'
  AND  populated > 0
  AND  profiled_at = (SELECT max(profiled_at) FROM dsc.column_profile
                      WHERE source_table = 'CHARGES');


-- Seed stg.arr from dsc.arr
-- Profile of arr taken 2026-09-20 21:56:44.322992: 97 of 338 columns populated.

BEGIN;

SET ROLE pp_owner;
CREATE TABLE IF NOT EXISTS stg.arr (
    address_city text,
    address_concat text,
    address_concat_display text,
    address_number text,
    address_state text,
    address_street text,
    address_zip text,
    age text,
    arraign_date text,
    arraigned_by text,
    arraign_time text,
    "arrest_#" text,
    arrest_date text,
    "arrest_#_display" text,
    arrestee_condition text,
    "arrest_#_rici" text,
    arrest_summary text,
    arrest_time text,
    _audit text,
    "bltr_#" text,
    bltr_calc_display text,
    "booking charge" text,
    "booking officer" text,
    condition_remand text,
    court_date text,
    court_date_to_prosecution text,
    court_decision text,
    created_by text,
    creation_date text,
    creation_date_timestamp text,
    creation_ip text,
    current_record_number text,
    day text,
    day_number text,
    dob text,
    eyes text,
    father_name text,
    _fkeyname_id text,
    _fkeypolicepro_id text,
    further_remand text,
    hair text,
    hgt text,
    id_other text,
    id_type text,
    image_text_2 text,
    image_text_3 text,
    image_text_4 text,
    image_text_5 text,
    image_text_6 text,
    image_text_7 text,
    image_text_search text,
    jail_cell text,
    jaildatereceived text,
    jaildatereleased text,
    jail_display_list text,
    jailofficerreceive text,
    jailofficerrelease text,
    jailtimereceived text,
    jailtimereleased text,
    "list_charges copy" text,
    "list_charges dispostion" text,
    list_charges_offense_only text,
    lock text,
    lock_display text,
    "marital status" text,
    modification_date_timestamp text,
    modified_by text,
    month text,
    month_2 text,
    month_name text,
    name_arrest_display text,
    name_first text,
    name_last text,
    name_mi text,
    photo_by text,
    "photo_ref_#" text,
    __pkeyarrest_id text,
    pkey_summary text,
    pob text,
    prints_by text,
    property_list text,
    _prosecutor text,
    rec_current text,
    rec_found_ct text,
    record_count_summ text,
    rec_tot text,
    rhtaudittraillog text,
    rhtaudittraillog_calc_display text,
    rhtaudittrailprevvalues text,
    rhtaudittrailtrigger text,
    scars text,
    sex text,
    ssn text,
    summon text,
    total_charges text,
    total_records text,
    year text,
    loaded_at timestamp NOT NULL DEFAULT clock_timestamp()
);
RESET ROLE;

DO $guard$
BEGIN
    IF 'f'::boolean THEN
        RAISE EXCEPTION 'The profile this script was generated from was row-limited'
            USING HINT = 'Fill rates reflect the sample, so real columns may be '
                         'missing from the table. Re-run fm_discover.py without '
                         '--limit, then regenerate.';
    END IF;
    IF EXISTS (SELECT 1 FROM stg.arr) THEN
        RAISE EXCEPTION 'stg.arr already holds rows'
            USING HINT = 'Seeding is for an empty table. Re-seeding means '
                         'truncating it first, deliberately, as an administrator.';
    END IF;
END $guard$;

INSERT INTO stg.arr (
       address_city,
       address_concat,
       address_concat_display,
       address_number,
       address_state,
       address_street,
       address_zip,
       age,
       arraign_date,
       arraigned_by,
       arraign_time,
       "arrest_#",
       arrest_date,
       "arrest_#_display",
       arrestee_condition,
       "arrest_#_rici",
       arrest_summary,
       arrest_time,
       _audit,
       "bltr_#",
       bltr_calc_display,
       "booking charge",
       "booking officer",
       condition_remand,
       court_date,
       court_date_to_prosecution,
       court_decision,
       created_by,
       creation_date,
       creation_date_timestamp,
       creation_ip,
       current_record_number,
       day,
       day_number,
       dob,
       eyes,
       father_name,
       _fkeyname_id,
       _fkeypolicepro_id,
       further_remand,
       hair,
       hgt,
       id_other,
       id_type,
       image_text_2,
       image_text_3,
       image_text_4,
       image_text_5,
       image_text_6,
       image_text_7,
       image_text_search,
       jail_cell,
       jaildatereceived,
       jaildatereleased,
       jail_display_list,
       jailofficerreceive,
       jailofficerrelease,
       jailtimereceived,
       jailtimereleased,
       "list_charges copy",
       "list_charges dispostion",
       list_charges_offense_only,
       lock,
       lock_display,
       "marital status",
       modification_date_timestamp,
       modified_by,
       month,
       month_2,
       month_name,
       name_arrest_display,
       name_first,
       name_last,
       name_mi,
       photo_by,
       "photo_ref_#",
       __pkeyarrest_id,
       pkey_summary,
       pob,
       prints_by,
       property_list,
       _prosecutor,
       rec_current,
       rec_found_ct,
       record_count_summ,
       rec_tot,
       rhtaudittraillog,
       rhtaudittraillog_calc_display,
       rhtaudittrailprevvalues,
       rhtaudittrailtrigger,
       scars,
       sex,
       ssn,
       summon,
       total_charges,
       total_records,
       year,
       loaded_at)
SELECT address_city,
       address_concat,
       address_concat_display,
       address_number,
       address_state,
       address_street,
       address_zip,
       age,
       arraign_date,
       arraigned_by,
       arraign_time,
       "arrest_#",
       arrest_date,
       "arrest_#_display",
       arrestee_condition,
       "arrest_#_rici",
       arrest_summary,
       arrest_time,
       _audit,
       "bltr_#",
       bltr_calc_display,
       "booking charge",
       "booking officer",
       condition_remand,
       court_date,
       court_date_to_prosecution,
       court_decision,
       created_by,
       creation_date,
       creation_date_timestamp,
       creation_ip,
       current_record_number,
       day,
       day_number,
       dob,
       eyes,
       father_name,
       _fkeyname_id,
       _fkeypolicepro_id,
       further_remand,
       hair,
       hgt,
       id_other,
       id_type,
       image_text_2,
       image_text_3,
       image_text_4,
       image_text_5,
       image_text_6,
       image_text_7,
       image_text_search,
       jail_cell,
       jaildatereceived,
       jaildatereleased,
       jail_display_list,
       jailofficerreceive,
       jailofficerrelease,
       jailtimereceived,
       jailtimereleased,
       "list_charges copy",
       "list_charges dispostion",
       list_charges_offense_only,
       lock,
       lock_display,
       "marital status",
       modification_date_timestamp,
       modified_by,
       month,
       month_2,
       month_name,
       name_arrest_display,
       name_first,
       name_last,
       name_mi,
       photo_by,
       "photo_ref_#",
       __pkeyarrest_id,
       pkey_summary,
       pob,
       prints_by,
       property_list,
       _prosecutor,
       rec_current,
       rec_found_ct,
       record_count_summ,
       rec_tot,
       rhtaudittraillog,
       rhtaudittraillog_calc_display,
       rhtaudittrailprevvalues,
       rhtaudittrailtrigger,
       scars,
       sex,
       ssn,
       summon,
       total_charges,
       total_records,
       year,
       loaded_at
FROM   dsc.arr;

DO $check$
DECLARE n_dsc bigint; n_stg bigint;
BEGIN
    SELECT count(*) INTO n_dsc FROM dsc.arr;
    SELECT count(*) INTO n_stg FROM stg.arr;
    IF n_dsc <> n_stg THEN
        RAISE EXCEPTION 'Row counts disagree: dsc %, stg %', n_dsc, n_stg;
    END IF;
    RAISE NOTICE 'Seeded %: % rows', 'stg.arr', n_stg;
END $check$;

COMMIT;
